baseURL = "https://blog.minoru.dev/"
languageCode = "ja"
DefaultContentLanguage = "jp"
title = "どらの引き出し"
enableEmoji = true
enableGitInfo = true
hasCJKLanguage = true

googleAnalytics = "UA-140449562-2"

theme = "PaperMod"

[permalinks]
    post = "/:year/:filename"

    [taxonomies]
        tag = "tags"
            archive = "archives"

[params]
    site_description = "一歩一歩、ゆっくりと。"
    twitter_id = "d0ra1998"
    github_id = "dora1998"
    website = "https://minoru.dev"

[markup.goldmark.renderer]
unsafe= true